### ISSUE TITLE
Clear new repo promoted action button

### ISSUE THREAD

**Issue by evelynhathaway** [oceanbit/GitShark#44]
When you have no repos in GitSark and re-open the app, the expanded new repo promoted action button is clear when opened for the first time.

<details>
<summary>Screenshots</summary>

![photo_2020-08-08_10-35-39](https://user-images.githubusercontent.com/38994283/89716602-2b51eb00-d963-11ea-807d-f88d60a3a3bf.jpg)

</details>

**Comment by crutchcorn** [comment]
I'm having difficulties reproducing this. Can you provide more step-by-step instructions for me? 😅 Further, what are the device/OS specs you're using?

**Comment by evelynhathaway** [comment]
No worries, I worded that confusingly.

Stock Android 10, Pixel 3XL, dark and light mode both do this

1. Delete all your repos, or don't have any to begin with
1. Force close GitShark
1. Open GitShark
1. Click `New Repository

Or at least that's how it happens for me...

**Comment by crutchcorn** [comment]
I'm still not able to reproduce :( That said, I know the expanded FAB component is extremely buggy on iOS, so I entirely believe this is happening. 

The fortunate part is that I suspect when I fix the FAB for iOS, it will automatically fix this problem

The unfortunate news is that I have a kinda lengthy backlog of items I need to fix first. Give me a week or two and I'll see what I can do

**Comment by crutchcorn** [comment]
@evelynhathaway are you able to retest this bug by any chance? This issue should be long-resolved by now

**Comment by evelynhathaway** [comment]
I'm sorry to say it still occurs 😔.

I can video call or setup a debugging environment if you'd like help reproducing this. 😊

![Screenshot_20210126-091515.png](https://user-images.githubusercontent.com/38994283/105879453-0c99ec00-5fb7-11eb-9b73-c717535fb30b.png)

**Comment by crutchcorn** [comment]
That'd be appreciated (to setup a dev environment with ya and walk through this together) - I've tested with 4 different hardware devices and 2 different emulated devices and sincerely cannot reproduce this issue 😅

**Comment by evelynhathaway** [comment]
I cannot reproduce in the public beta in either light or dark mode! 🎉

**Comment by crutchcorn** [comment]
Yes!! I worked so hard on reworking the entirety of the component right up until the deadline! Super super happy that this is resolved. Thank you so much for testing @evelynhathaway
